--[[
    Rayfield to WindUI Auto-Generator
    Tự động chuyển đổi và TẠO SCRIPT WINDUI MỚI
    Script mới sẽ được copy vào clipboard để sử dụng độc lập
]]

-- Load WindUI
local WindUI = loadstring(game:HttpGet("https://github.com/Footagesus/WindUI/releases/latest/download/main.lua"))()

-- Generator để tạo code WindUI
local CodeGenerator = {}
CodeGenerator.Lines = {}
CodeGenerator.Indentation = 0

function CodeGenerator:AddLine(code)
    local indent = string.rep("    ", self.Indentation)
    table.insert(self.Lines, indent .. code)
end

function CodeGenerator:Indent()
    self.Indentation = self.Indentation + 1
end

function CodeGenerator:Unindent()
    self.Indentation = math.max(0, self.Indentation - 1)
end

function CodeGenerator:GetCode()
    return table.concat(self.Lines, "\n")
end

function CodeGenerator:Reset()
    self.Lines = {}
    self.Indentation = 0
end

-- Utility: Convert value sang string code
local function ValueToCode(value)
    if type(value) == "string" then
        return string.format("%q", value)
    elseif type(value) == "number" then
        return tostring(value)
    elseif type(value) == "boolean" then
        return tostring(value)
    elseif type(value) == "table" then
        local parts = {}
        for k, v in pairs(value) do
            if type(k) == "number" then
                table.insert(parts, ValueToCode(v))
            else
                table.insert(parts, string.format("[%s] = %s", ValueToCode(k), ValueToCode(v)))
            end
        end
        return "{" .. table.concat(parts, ", ") .. "}"
    elseif typeof(value) == "Color3" then
        return string.format("Color3.fromRGB(%d, %d, %d)", 
            math.floor(value.R * 255), 
            math.floor(value.G * 255), 
            math.floor(value.B * 255))
    elseif typeof(value) == "UDim2" then
        return string.format("UDim2.fromOffset(%d, %d)", value.X.Offset, value.Y.Offset)
    elseif typeof(value) == "EnumItem" then
        return tostring(value)
    else
        return "nil"
    end
end

-- Rayfield Adapter với Code Generation
local RayfieldAdapter = {}
RayfieldAdapter.Flags = {}

local function ConvertIcon(icon)
    if type(icon) == "number" or (type(icon) == "string" and icon:match("^%d+$")) then
        return "circle"
    end
    return icon or "circle"
end

-- CreateWindow với Code Generation
function RayfieldAdapter:CreateWindow(config)
    local WindowAdapter = {}
    WindowAdapter._callbacks = {} -- Lưu callbacks để generate
    WindowAdapter._elements = {} -- Lưu elements để generate
    
    -- Bắt đầu generate code
    CodeGenerator:Reset()
    CodeGenerator:AddLine("-- Auto-generated WindUI Script")
    CodeGenerator:AddLine("-- Generated by Rayfield to WindUI Converter")
    CodeGenerator:AddLine("-- Host by VTriP Official")
    CodeGenerator:AddLine("")
    CodeGenerator:AddLine("local WindUI = loadstring(game:HttpGet('https://github.com/Footagesus/WindUI/releases/latest/download/main.lua'))()")
    CodeGenerator:AddLine("")
    
    -- Tạo theme
    CodeGenerator:AddLine("-- Custom Theme")
    CodeGenerator:AddLine("WindUI:AddTheme({")
    CodeGenerator:Indent()
    CodeGenerator:AddLine("Name = 'VTriP Dark',")
    CodeGenerator:AddLine("Accent = WindUI:Gradient({")
    CodeGenerator:Indent()
    CodeGenerator:AddLine("['0'] = { Color = Color3.fromHex('#040040'), Transparency = 0 },")
    CodeGenerator:AddLine("['100'] = { Color = Color3.fromHex('#473BE8'), Transparency = 0.42 },")
    CodeGenerator:Unindent()
    CodeGenerator:AddLine("}, { Rotation = 104 }),")
    CodeGenerator:AddLine("Background = WindUI:Gradient({")
    CodeGenerator:Indent()
    CodeGenerator:AddLine("['0'] = { Color = Color3.fromHex('#040040'), Transparency = 0 },")
    CodeGenerator:AddLine("['100'] = { Color = Color3.fromHex('#473BE8'), Transparency = 0.42 },")
    CodeGenerator:Unindent()
    CodeGenerator:AddLine("}, { Rotation = 104 }),")
    CodeGenerator:Unindent()
    CodeGenerator:AddLine("})")
    CodeGenerator:AddLine("")
    
    -- Tạo window
    local windowTitle = config.Name or "Window"
    if windowTitle:find("Flash Hub") then
        windowTitle = windowTitle:gsub("Flash Hub", "VTriP")
    end
    
    CodeGenerator:AddLine("-- Create Window")
    CodeGenerator:AddLine("local Window = WindUI:CreateWindow({")
    CodeGenerator:Indent()
    CodeGenerator:AddLine(string.format("Title = %s,", ValueToCode(windowTitle)))
    CodeGenerator:AddLine(string.format("Icon = %s,", ValueToCode(ConvertIcon(config.Icon))))
    CodeGenerator:AddLine("Author = 'Host By VTriP Official',")
    CodeGenerator:AddLine(string.format("Folder = %s,", ValueToCode((config.ConfigurationSaving and config.ConfigurationSaving.FolderName) or "WindUIConfig")))
    CodeGenerator:AddLine("Size = UDim2.fromOffset(580, 460),")
    CodeGenerator:AddLine("Transparent = true,")
    CodeGenerator:AddLine("Theme = 'VTriP Dark',")
    CodeGenerator:AddLine("Resizable = true,")
    CodeGenerator:AddLine("SideBarWidth = 200,")
    
    if config.KeySystem then
        CodeGenerator:AddLine("KeySystem = {")
        CodeGenerator:Indent()
        CodeGenerator:AddLine(string.format("Key = %s,", ValueToCode(config.KeySettings.Key or {})))
        CodeGenerator:AddLine(string.format("Note = %s,", ValueToCode(config.KeySettings.Note or "No key note")))
        CodeGenerator:AddLine(string.format("SaveKey = %s,", ValueToCode(config.KeySettings.SaveKey or false)))
        CodeGenerator:Unindent()
        CodeGenerator:AddLine("},")
    end
    
    CodeGenerator:Unindent()
    CodeGenerator:AddLine("})")
    CodeGenerator:AddLine("")
    
    -- Open Button
    CodeGenerator:AddLine("-- Customize Open Button")
    CodeGenerator:AddLine("Window:EditOpenButton({")
    CodeGenerator:Indent()
    CodeGenerator:AddLine("Title = 'Open VTriP',")
    CodeGenerator:AddLine(string.format("Icon = %s,", ValueToCode(ConvertIcon(config.Icon))))
    CodeGenerator:AddLine("CornerRadius = UDim.new(0, 16),")
    CodeGenerator:AddLine("StrokeThickness = 2,")
    CodeGenerator:AddLine("Color = ColorSequence.new(Color3.fromHex('FF0F7B'), Color3.fromHex('F89B29')),")
    CodeGenerator:Unindent()
    CodeGenerator:AddLine("})")
    CodeGenerator:AddLine("")
    
    -- Toggle Key
    if config.ToggleUIKeybind then
        local keyCode = config.ToggleUIKeybind
        if type(keyCode) == "string" then
            CodeGenerator:AddLine(string.format("Window:SetToggleKey(Enum.KeyCode.%s)", keyCode))
        else
            CodeGenerator:AddLine(string.format("Window:SetToggleKey(%s)", tostring(keyCode)))
        end
        CodeGenerator:AddLine("")
    end
    
    -- Tạo WindUI window thật
    local windConfig = {
        Title = windowTitle,
        Icon = ConvertIcon(config.Icon),
        Author = "Host By VTriP Official",
        Folder = (config.ConfigurationSaving and config.ConfigurationSaving.FolderName) or "WindUIConfig",
        Size = UDim2.fromOffset(580, 460),
        Transparent = true,
        Theme = "VTriP Dark",
        Resizable = true,
        SideBarWidth = 200,
    }
    
    if config.KeySystem then
        windConfig.KeySystem = {
            Key = config.KeySettings.Key or {},
            Note = config.KeySettings.Note or "No key note",
            SaveKey = config.KeySettings.SaveKey or false,
        }
    end
    
    local Window = WindUI:CreateWindow(windConfig)
    
    Window:EditOpenButton({
        Title = "Open VTriP",
        Icon = ConvertIcon(config.Icon),
        CornerRadius = UDim.new(0, 16),
        StrokeThickness = 2,
        Color = ColorSequence.new(Color3.fromHex("FF0F7B"), Color3.fromHex("F89B29")),
    })
    
    if config.ToggleUIKeybind then
        local keyCode = config.ToggleUIKeybind
        if type(keyCode) == "string" then
            Window:SetToggleKey(Enum.KeyCode[keyCode])
        else
            Window:SetToggleKey(keyCode)
        end
    end
    
    WindowAdapter._windWindow = Window
    WindowAdapter._config = config
    WindowAdapter._callbackCounter = 0
    
    -- CreateTab với generation
    function WindowAdapter:CreateTab(name, icon)
        local TabAdapter = {}
        TabAdapter._tabName = name
        TabAdapter._callbacks = {}
        
        -- Generate tab code
        CodeGenerator:AddLine(string.format("-- Tab: %s", name))
        CodeGenerator:AddLine(string.format("local Tab_%s = Window:Tab({", name:gsub("%s+", "_")))
        CodeGenerator:Indent()
        CodeGenerator:AddLine(string.format("Title = %s,", ValueToCode(name)))
        CodeGenerator:AddLine(string.format("Icon = %s,", ValueToCode(ConvertIcon(icon))))
        CodeGenerator:Unindent()
        CodeGenerator:AddLine("})")
        CodeGenerator:AddLine("")
        
        local Tab = Window:Tab({
            Title = name,
            Icon = ConvertIcon(icon),
        })
        
        TabAdapter._windTab = Tab
        
        -- CreateButton với callback generation
        function TabAdapter:CreateButton(config)
            local callbackName = string.format("Button_%s_Callback", name:gsub("%s+", "_"))
            self._callbacks[callbackName] = config.Callback
            
            -- Generate callback function
            if config.Callback then
                WindowAdapter._callbackCounter = WindowAdapter._callbackCounter + 1
                CodeGenerator:AddLine(string.format("local function %s()", callbackName))
                CodeGenerator:Indent()
                CodeGenerator:AddLine("-- Your callback code here")
                if type(config.Callback) == "function" then
                    -- Không thể serialize function, chỉ để placeholder
                    CodeGenerator:AddLine("-- Original callback from Rayfield script")
                end
                CodeGenerator:Unindent()
                CodeGenerator:AddLine("end")
                CodeGenerator:AddLine("")
            end
            
            -- Generate button
            CodeGenerator:AddLine(string.format("Tab_%s:Button({", name:gsub("%s+", "_")))
            CodeGenerator:Indent()
            CodeGenerator:AddLine(string.format("Title = %s,", ValueToCode(config.Name)))
            CodeGenerator:AddLine(string.format("Desc = %s,", ValueToCode(config.Desc or "")))
            if config.Callback then
                CodeGenerator:AddLine(string.format("Callback = %s,", callbackName))
            end
            CodeGenerator:Unindent()
            CodeGenerator:AddLine("})")
            CodeGenerator:AddLine("")
            
            return Tab:Button({
                Title = config.Name,
                Desc = config.Desc or "",
                Callback = config.Callback or function() end
            })
        end
        
        -- CreateToggle với callback generation
        function TabAdapter:CreateToggle(config)
            local callbackName = string.format("Toggle_%s_%s_Callback", 
                name:gsub("%s+", "_"), 
                config.Name:gsub("%s+", "_"))
            
            if config.Callback then
                WindowAdapter._callbackCounter = WindowAdapter._callbackCounter + 1
                CodeGenerator:AddLine(string.format("local function %s(state)", callbackName))
                CodeGenerator:Indent()
                CodeGenerator:AddLine("-- Your callback code here")
                CodeGenerator:AddLine("-- state: boolean")
                CodeGenerator:Unindent()
                CodeGenerator:AddLine("end")
                CodeGenerator:AddLine("")
            end
            
            CodeGenerator:AddLine(string.format("Tab_%s:Toggle({", name:gsub("%s+", "_")))
            CodeGenerator:Indent()
            CodeGenerator:AddLine(string.format("Title = %s,", ValueToCode(config.Name)))
            CodeGenerator:AddLine(string.format("Desc = %s,", ValueToCode(config.Desc or "")))
            CodeGenerator:AddLine(string.format("Value = %s,", ValueToCode(config.CurrentValue or false)))
            if config.Callback then
                CodeGenerator:AddLine(string.format("Callback = %s,", callbackName))
            end
            CodeGenerator:Unindent()
            CodeGenerator:AddLine("})")
            CodeGenerator:AddLine("")
            
            return Tab:Toggle({
                Title = config.Name,
                Desc = config.Desc or "",
                Value = config.CurrentValue or false,
                Callback = config.Callback or function() end
            })
        end
        
        -- CreateSlider với callback generation
        function TabAdapter:CreateSlider(config)
            local callbackName = string.format("Slider_%s_%s_Callback", 
                name:gsub("%s+", "_"), 
                config.Name:gsub("%s+", "_"))
            
            if config.Callback then
                WindowAdapter._callbackCounter = WindowAdapter._callbackCounter + 1
                CodeGenerator:AddLine(string.format("local function %s(value)", callbackName))
                CodeGenerator:Indent()
                CodeGenerator:AddLine("-- Your callback code here")
                CodeGenerator:AddLine("-- value: number")
                CodeGenerator:Unindent()
                CodeGenerator:AddLine("end")
                CodeGenerator:AddLine("")
            end
            
            CodeGenerator:AddLine(string.format("Tab_%s:Slider({", name:gsub("%s+", "_")))
            CodeGenerator:Indent()
            CodeGenerator:AddLine(string.format("Title = %s,", ValueToCode(config.Name)))
            CodeGenerator:AddLine(string.format("Step = %s,", ValueToCode(config.Increment or 1)))
            CodeGenerator:AddLine("Value = {")
            CodeGenerator:Indent()
            CodeGenerator:AddLine(string.format("Min = %s,", ValueToCode(config.Range[1])))
            CodeGenerator:AddLine(string.format("Max = %s,", ValueToCode(config.Range[2])))
            CodeGenerator:AddLine(string.format("Default = %s,", ValueToCode(config.CurrentValue or config.Range[1])))
            CodeGenerator:Unindent()
            CodeGenerator:AddLine("},")
            if config.Callback then
                CodeGenerator:AddLine(string.format("Callback = %s,", callbackName))
            end
            CodeGenerator:Unindent()
            CodeGenerator:AddLine("})")
            CodeGenerator:AddLine("")
            
            return Tab:Slider({
                Title = config.Name,
                Step = config.Increment or 1,
                Value = {
                    Min = config.Range[1],
                    Max = config.Range[2],
                    Default = config.CurrentValue or config.Range[1],
                },
                Callback = config.Callback or function() end
            })
        end
        
        -- Các element khác tương tự...
        function TabAdapter:CreateDropdown(config)
            local callbackName = string.format("Dropdown_%s_%s_Callback", 
                name:gsub("%s+", "_"), 
                config.Name:gsub("%s+", "_"))
            
            if config.Callback then
                WindowAdapter._callbackCounter = WindowAdapter._callbackCounter + 1
                CodeGenerator:AddLine(string.format("local function %s(options)", callbackName))
                CodeGenerator:Indent()
                CodeGenerator:AddLine("-- Your callback code here")
                CodeGenerator:AddLine("-- options: table or string")
                CodeGenerator:Unindent()
                CodeGenerator:AddLine("end")
                CodeGenerator:AddLine("")
            end
            
            local isMulti = config.MultipleOptions or false
            local defaultValue
            
            if isMulti then
                defaultValue = type(config.CurrentOption) == "table" and config.CurrentOption or {config.CurrentOption or ""}
            else
                defaultValue = type(config.CurrentOption) == "string" and config.CurrentOption or (config.Options and config.Options[1] or "")
            end
            
            CodeGenerator:AddLine(string.format("Tab_%s:Dropdown({", name:gsub("%s+", "_")))
            CodeGenerator:Indent()
            CodeGenerator:AddLine(string.format("Title = %s,", ValueToCode(config.Name)))
            CodeGenerator:AddLine(string.format("Values = %s,", ValueToCode(config.Options or {})))
            CodeGenerator:AddLine(string.format("Value = %s,", ValueToCode(defaultValue)))
            CodeGenerator:AddLine(string.format("Multi = %s,", ValueToCode(isMulti)))
            if config.Callback then
                CodeGenerator:AddLine(string.format("Callback = %s,", callbackName))
            end
            CodeGenerator:Unindent()
            CodeGenerator:AddLine("})")
            CodeGenerator:AddLine("")
            
            return Tab:Dropdown({
                Title = config.Name,
                Values = config.Options or {},
                Value = defaultValue,
                Multi = isMulti,
                Callback = config.Callback or function() end
            })
        end
        
        -- Input, ColorPicker, Keybind tương tự...
        function TabAdapter:CreateInput(config)
            local callbackName = string.format("Input_%s_%s_Callback", 
                name:gsub("%s+", "_"), 
                config.Name:gsub("%s+", "_"))
            
            if config.Callback then
                WindowAdapter._callbackCounter = WindowAdapter._callbackCounter + 1
                CodeGenerator:AddLine(string.format("local function %s(text)", callbackName))
                CodeGenerator:Indent()
                CodeGenerator:AddLine("-- Your callback code here")
                CodeGenerator:Unindent()
                CodeGenerator:AddLine("end")
                CodeGenerator:AddLine("")
            end
            
            CodeGenerator:AddLine(string.format("Tab_%s:Input({", name:gsub("%s+", "_")))
            CodeGenerator:Indent()
            CodeGenerator:AddLine(string.format("Title = %s,", ValueToCode(config.Name)))
            CodeGenerator:AddLine(string.format("Placeholder = %s,", ValueToCode(config.PlaceholderText or "")))
            CodeGenerator:AddLine(string.format("Value = %s,", ValueToCode(config.CurrentValue or "")))
            if config.Callback then
                CodeGenerator:AddLine(string.format("Callback = %s,", callbackName))
            end
            CodeGenerator:Unindent()
            CodeGenerator:AddLine("})")
            CodeGenerator:AddLine("")
            
            return Tab:Input({
                Title = config.Name,
                Placeholder = config.PlaceholderText or "",
                Value = config.CurrentValue or "",
                Callback = config.Callback or function() end
            })
        end
        
        return TabAdapter
    end
    
    -- Khi window đóng/script kết thúc, copy code vào clipboard
    function WindowAdapter:Finalize()
        CodeGenerator:AddLine("-- Script generated successfully!")
        CodeGenerator:AddLine("-- Copy this entire script and use it independently")
        
        local generatedCode = CodeGenerator:GetCode()
        
        -- Copy vào clipboard
        if setclipboard then
            setclipboard(generatedCode)
            WindUI:Notify({
                Title = "Script Generated!",
                Content = "WindUI script đã được tạo và copy vào clipboard. Paste để sử dụng độc lập!",
                Duration = 10,
                Icon = "check",
            })
        else
            WindUI:Notify({
                Title = "Script Generated!",
                Content = "Script đã tạo xong nhưng executor không hỗ trợ clipboard. Check console (F9).",
                Duration = 10,
                Icon = "alert-circle",
            })
            print("=== GENERATED WINDUI SCRIPT ===")
            print(generatedCode)
            print("=== END OF SCRIPT ===")
        end
    end
    
    return WindowAdapter
end

function RayfieldAdapter:Notify(config)
    WindUI:Notify({
        Title = config.Title or "Notification",
        Content = config.Content or "",
        Duration = config.Duration or 5,
        Icon = ConvertIcon(config.Image),
    })
end

return RayfieldAdapter
